# Generated by Django 2.2 on 2021-05-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
    ]
